EXP:
  EXP_ID: "libero_subset"
  MODEL: "qwen"
  LR_SCHED: "cosine_anneal"
  AMP: True
  OPTIMIZER: "adamw"

TRAIN:
  lr: 2e-4
  num_epochs: 50
  clip_grad_norm: 1.0
  l2: 1e-4

LR_SCHED:
  lr_clip: 1e-6

EXP_EXTRA:
  save_ckp: 5
  save_last_ckpt: True

DATALOADER:
  batch_size: 8
  num_workers: 3
  ROBOVERSE:
    cfg_path: libs/RoboVerse/roboverse/configs/img_libero_aug_subset.yaml
    cfg_opts: IMAGE.crop_img:0.875:IMAGE.img_size:224:IMAGE.cam_list:('3p1','3p2')

MODEL:
  QWEN:
    add_vision_id: True
    use_lora: True
    lora_config: default
    lora_rank: 16
    use_qlora: False
    use_flash_attention_2: False
    rgb_img_size: 224,224
    original_action_dim: 7
    action_mask_aug_per: 0.4
    num_cam: 2
    tiled_rgb_imgs: True
